spring:
  application:
    name: recommendation-service
  datasource:
    url: jdbc:mysql://localhost:3306/recommendationdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082
